### ISSUE TITLE
Why only for 8 version?

### ISSUE THREAD

**Issue by typo3ua** [saschaende/typo3-users#1]
I see your the extension only for 8 version, why?

**Comment by saschaende** [comment]
It is still in development and i am developing in a 8 environment :) I will test and make it compatible with 9 after it works with 8.

**Comment by typo3ua** [comment]
Wow, you are musician and developer, you are created great website. You are, Well done! Thank you for reply. I wish you good luck and your music will be on top hits...

**Comment by saschaende** [comment]
Thank you! :) I hope you will like the final extension when its ready. I think, some weeks and it will be stable.
