### ISSUE TITLE
I can not translate text in the email messages

### ISSUE THREAD

**Issue by typo3ua** [saschaende/typo3-users#11]
![copyright_email_ext_user](https://user-images.githubusercontent.com/638022/57585526-049fcd00-74f2-11e9-80f3-58593034e0eb.png)

**Comment by saschaende** [comment]
Fixed in MASTER

**Comment by typo3ua** [comment]
I already added this in the `uk.locallang.xlf`.

If you are adding new language labels (trans unit) in the `en.locallang.xlf` add it also too in the `uk.locallang.xlf`. I will translate them later.

**Comment by saschaende** [comment]
> If you are adding new language labels (trans unit) in the en.locallang.xlf add it also in the uk.locallang.xlf. I will translate them later.

I did

**Comment by typo3ua** [comment]
I already translated added the new lines
