### ISSUE TITLE
Translations on TYPO3 forge

### ISSUE THREAD

**Issue by saschaende** [saschaende/typo3-users#13]
@typo3ua , i started a task, perhaps they will add it:
https://forge.typo3.org/issues/88349

**Comment by typo3ua** [comment]
I do not know exactly but I think it is not necessary. Everyone is using github.com now.

Maybe is it need for that to get to the server https://translation.typo3.org

**Comment by saschaende** [comment]
Opening a task is the prerequisite for the translation tool. 

https://forge.typo3.org/projects/team-translation

## Policy for new extensions

Setting up a project on the translation server requires some manual steps. In order to get most efficiency and to ensure the continued existence of added extensions, new extensions to be added are subject to following requirements:

The extension candidate must be publicly available in TER
The extension candidate must be marked as "stable" in TER (meaning it is actively supported)
The extension candidate should have a minimum user base of 120 regular installs
A ticket created by the maintainer of the extension is created for asking this

**Comment by typo3ua** [comment]
:) well then will be waiting for a reply from `Team Translation`

**Comment by saschaende** [comment]
Its denied, because this extension is beta and the policy is "only stable".
