### ISSUE TITLE
Accessibility of function `Change email`

### ISSUE THREAD

**Issue by typo3ua** [saschaende/typo3-users#14]
I guess `Plugin: Change email` must available not only for registered users and also for only users who logged.

**Comment by saschaende** [comment]
This is a plugin only for registered users.

**Comment by typo3ua** [comment]
Yes, I understand. 

And therefore I write that `not registered user` and `not logged user` do not have to see the form `Change email`. I must see information for example. `You are not logged. Login please` and add button `Login`

It is just a suggestion. Maybe do you have something other?

**Comment by saschaende** [comment]
Yes thats planned and you will todo markers in the code, yet.

I will also update the documentation for the next public release, so everybody knows what to to and how to do.

**Comment by saschaende** [comment]
Fixed now, you get an error when you are not logged in
