### ISSUE TITLE
Plugin: Change email - Error: Call to a member function setUsersNewemail() on null

### ISSUE THREAD

**Issue by typo3ua** [saschaende/typo3-users#15]
### I entered the new e-mail in the field of `E-mail` and I get the error:

![change_email_ext_user](https://user-images.githubusercontent.com/638022/57726342-dbb93c80-7697-11e9-9fbe-5a182af5bb2c.png)

**Comment by saschaende** [comment]
1. This oligin is still in development and does not work at all
2. If you update the extension manually you have to dump autoload files in typo3

**Comment by typo3ua** [comment]
Okay! I will make it...

**Comment by typo3ua** [comment]
Exactly, the error appears is then when the user not logged.

**Comment by typo3ua** [comment]
I tested all the steps in the 'Change email`. The function 'Change email' not work yet.

I see that not work the last step

![change_email_message_ext_user](https://user-images.githubusercontent.com/638022/57732824-994b2c00-76a6-11e9-9837-7a61b9718c3d.png)

**Comment by saschaende** [comment]
As i said, the development of this plugin is not finalized, it will not work.

I will continue next week when i have time.

Also translations and templates can change (even completely).

**Comment by saschaende** [comment]
Fixed now, you get an error when you are not logged in
