### ISSUE TITLE
[BUG] If plugin "Login" as "Content Element - Shortcut"

### ISSUE THREAD

**Issue by typo3ua** [saschaende/typo3-users#23]
If the plugin "Login" added to content as the "Content Element - Shortcut" from another page, login does not possible.

![login_shortcut](https://user-images.githubusercontent.com/638022/60003451-67e55900-9673-11e9-9444-6e9a61526741.png)

**Comment by saschaende** [comment]
Actually the plugins are not intended to be used in this way. Just follow the readme and add the plugins as explained in the documentation.

**Comment by typo3ua** [comment]
Yes, I know about the readme, but I needed exactly this possibility... okay! never mind... it does not matter. Thanks!

close the issue, please

**Comment by saschaende** [comment]
If you have suggestions on how to solve the problem, I would be happy about a commit. For me this is not on the priority list at the moment, because I don't need it myself.
