### ISSUE TITLE
Dashboard plugin with TYPO3 9 and multilanguage

### ISSUE THREAD

**Issue by saschaende** [saschaende/typo3-users#24]
Dashboard plugin only shows content from the default language.

**Comment by Pyxwyz** [comment]
Guess "just" something wrong with xlf-files and the templates.  i'm new to it, but at least the xlf-files are diffrent from other extensions, also i found that the translation-tags should be covered with "f:format.raw"?

**Comment by saschaende** [comment]
@Pyxwyz No this does not have to do with format:raw. You need format:raw if html should be allowed in translations.

**Comment by tomaszzablocki** [comment]
First of all, thanks for the great work on the plugin.
This is not just a dashboard problem, but a general translation problem.
According to this https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Internationalization/XliffFormat.html#basics and this https://forge.typo3.org/issues/78095
one cannot use en.locallang.xlf files:
"Note that the original file must always be in english, so it is not allowed to create a file with the prefix “en” e.g. en.locallang.xlf."
Is there a chance to change language files in the near future?

**Comment by saschaende** [comment]
Yes, this is planned in near future.

**Comment by saschaende** [comment]
> First of all, thanks for the great work on the plugin.
> This is not just a dashboard problem, but a general translation problem.
> According to this https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Internationalization/XliffFormat.html#basics and this https://forge.typo3.org/issues/78095
> one cannot use en.locallang.xlf files:
> "Note that the original file must always be in english, so it is not allowed to create a file with the prefix “en” e.g. en.locallang.xlf."
> With current files structure english translations do not work.
> Is there a chance to change language files in the near future?

This is fixed now in the latest version 0.8.6
