### ISSUE TITLE
Adding static_info_tables to composer.json

### ISSUE THREAD

**Issue by hrdyy** [saschaende/typo3-users#26]
https://github.com/saschaende/typo3-users/blob/0dd4604f52aaea6c28a159310f2d1727b45ccfb6/composer.json#L10

Add static_info_tables to the composer.json dependencies

```json
  "require": {
    "typo3/cms-core": ">=8.7.0 <10.0.0",
    "saschaende/t3helpers": ">=0.9.28",
    "sjbr/static-info-tables": "~6.7"
  }
```

**Comment by saschaende** [comment]
Thank you, i committed it.

**Comment by saschaende** [comment]
https://extensions.typo3.org/extension/users/
