### ISSUE TITLE
Can not login or change the profile 

### ISSUE THREAD

**Issue by docmcfly** [saschaende/typo3-users#27]
Hallo Sascha, 

irgendetwas mache ich falsch. Ich habe Typo3 9.5.10 im Einsatz. Als Erweiterungen haben ich das bootstrap_package und users. 

Leider kann ich mich nicht einloggen und das Profil (Straße, Wohnort etc) eines Webusers kann ich auch nicht ändern. Das Formular ist leer.

Mit dem normalen Anmeldeformular kann ich mich einloggen.

Wenn ich Deine Anleitung richtig verstanden habe, muss ich ja nicht viel tun, damit es geht. Die Plugins werden ja auch korrekt angezeigt. Daran kann es also nicht liegen. 

Hast Du noch einen Tipp für mich? Oder welche Infos kann ich Dir bereitstellen, damit Du den Fehler eingrenzen kannst... 

Danke für die Hilfe und schöne größe aus Letter vor den Toren von Hannover.
Gruß Clemens 

----------
Hello, Sascha, 

I'm doing something wrong. I have Typo3 9.5.10 in use. As extensions I have the bootstrap_package and users. 

Unfortunately I can't log in and I can't change the profile (street, place of residence etc) of a web user. The form is empty.

With the normal registration form I can log in.

If I have understood your instructions correctly, I don't have to do much to make it work. The plugins are displayed correctly. So it can't be because of that. 

Do you have another tip for me? Or which information can I provide you, so that you can limit the error... 

Thanks for the help and nice size from Letter at the gates of Hannover.
Greeting Clemens 

Translated with www.DeepL.com/Translator

**Comment by saschaende** [comment]
Es ist nicht möglich, hier Einschätzungen abzugeben warum es nicht funktioniert. Das naheliegendste sind falsche Einstellungen oder fehlende Integration der TypoScript Dateien.
Die Extension läuft in TYPO3 9 Systemen eigentlich.

Sollten alle Stricke reissen, kann ich mir das auf Deinem System anschauen. Normalerweise rechne ich das dann stundenweise ab. Sollte es sich definitiv um einen Fehler in der Extension handeln, berechne ich nichts.

**Comment by docmcfly** [comment]
Hallo Sascha,

ich hab ein wenig analysiert und habe herausgefunden, warum ich ich keine Profile ändern kann. 

In meinem Szenario werden die usersnames nicht von den Front-End-Usern selbst bestimmt sondern vom Admin fest vorgegeben. Die vergebenen usernames beinhalten immer einen Punkt als Trennzeichen. Das ist laut Typo3 auch erlaubt.    

Im ChangeprofileController.php schlägt nun folgende Fehlerprüfung zu: 
// Sonderzeichen im Username
        if (preg_match('/[^a-zA-Z0-9]/', $user->getUsername()) == 1) {
            $errors['username'][] = '2';
        }

Das ist in zweierlei Punkten von Nachteil:

Erstens: 
In meinem Formular taucht das Feld mit dem username gar nicht auf. Denn es ist beim mir nicht zulässig diesen zu ändern. Darum kann die Fehlermeldung auch nicht angezeigt werden. 
Vorschlag: Es sollten nur die Felder geprüft werden, welche auch im Formular auftauchen. (Außer es gibt da einen wichtigen Grund den ich hier nicht sehe, weil mir vielleicht das nötige Hintergrundwissen fehlt.  Da lasse ich mich auch gerne eines Besseren belehren.)

Zweitens: 
Einen eigenen regulären Ausdruck zu verwenden ist nicht praktisch, da dieser nachgepflegt werden muss, wenn bei Typo3 sich die Regeln für gültige Usernames ändert. Hier wäre es vielleicht ratsam, falls möglich die Prüfung von Typo3 direkt zu verwenden. 
Die passende Stelle im Typo3-Coding habe ich nicht gefunden. Wenn diese in einem fluid-Konstrukt versteckt ist, ist das natürlich schlecht. Dann kann man vielleicht  sich da den Regulären Ausdruck rauskopieren und in einem Kommentar die Quelle dieses Regel notieren.  

Ich werden jetzt erst mal als kleinen Patch den regulären Ausdruck so ändern:  '/[^\.a-zA-Z0-9]/'

Und hoffe auf ein baldiges Update. 

Vielleicht erzeugen diese Usernames auch mein Problem beim Login. Ich melde mich, wenn ich was finde. 

Aktuell geht das login wieder. Ich hab an vielen Stellen herumgespielt. Hatte auch zwischen durch ein Redirekt-Overflow provoziert. Vielleicht kann ich die Rahmenbedingung für diesen Fehler noch genauer spezifizieren. 

Einen schönen Feiertag 
Clemens

**Comment by docmcfly** [comment]
Hi Sascha, 

Nachtrag: ich hab den Fehler gefunden, warum das Login nicht funktioniert hat. 
Beim Webseiten-Nutzer kann man im Reiter "Erweitert" den "Datensatztyp[tx_extbase_type]" festlegen. 

Dort war noch "Tx_Extbase_Domain_Model_FrontendUser" ausgewählt. 

In dem Fall  hat scheinbar Deine Erweiterung keinen Zugriff auf das FE-User-Profil. 

Nochmals Grüße 
Clemens

**Comment by saschaende** [comment]
Hi,

Sonderzeichen sind in dieser Extension in Benutzernamen eigentlich mit Absicht aus vielen Gründen nicht erwünscht. Die einzige Möglichkeit wäre, dies konfigurierbar zu machen - was eh geplant ist.

So wären z.B. Benutzernamen "saschaende" oder auch "sascha.ende" möglich, was genau der Grund war, dass dies nicht erlaubt ist.

Die Extension wurde vorwiegend zur Nutzung auf Filmmusic.io entwickelt, wo dies eben nicht erlaubt ist.

**Comment by docmcfly** [comment]
Nichts desto trotz muss der Benutzername ja nicht geprüft werden, wenn ich diesen in meinem Profil-Änderungsformular eh nicht anzeige  bzw. ändern kann. Ich halte es für ein seltsames Pattern, wenn man seinen login-Namen nachträglich ändern kann (, aber da weiß ich nicht was Filmemusic.io so vorgibt ;-) 

Jedenfalls danke für Deine Erweiterung. Ich werde diese als Inspiration verwenden eine eigene Erweiterung zu schreiben. So ein gutes rechhaltiges Beispiel ist besser als manche Literatur.  

Schöne Grüße 
Clemens

**Comment by saschaende** [comment]
Genau darum habe ich auch selbst die users Extension geschrieben weil ich nichts gefunden habe, was für meine Bedürfnisse passte :)
Da ich selbst open Source nutze, wollte ich mit dieser Extension was "zurückgeben", für alle die es eventuell benötigen oder wo es vom Anwendungszweck passt.

Mangels Zeit und vor allem weil ich es alleine entwickle, kann ich darum nur begrenzt auf Userwünsche eingehen, wenn ich diese selbst nicht benötige.

**Comment by saschaende** [comment]
Man muss dazu aber auch sagen, dass sich diese Extension wahrscheinlich in vielen Fällen (NOCH) nicht dazu eignet, auf ein bestehendenes Benutzersystem aufzubauen - da TYPO3 z.B. auch mehrere Accounts mit der gleichen E-Mail Adresse erlaubt, was in meiner Extension ausdrücklich nicht erwünscht ist. Es ist also eher für neue Webseiten gedacht, die ähnliche Vorstellungen wie ich von einem Communitysystem haben.

**Comment by docmcfly** [comment]
Eine Frage hätte ich da noch: Wie hast Du mit der Extension-Entwicklung begonnen. Als ich damals Extension gebaut haben (Typo3 3.5 & 4.5) habe ich Kickstarter verwendet. Welche Extension verwendet man denn heute so zu Extenstionbau? 

Danke Clemens

**Comment by saschaende** [comment]
Also meistens mit dem Extension Builder und danach alles per Hand. Nutze den aber nur, wenn ich komplizierte Tabellen und Relationen habe.

In meinem Blog findest Du vielleicht noch hilfreiche Dinge (seit ich mit TYPO3 angefangen habe, poste ich dort immer mal was): https://typo3.sascha-ende.de/

**Comment by saschaende** [comment]
https://extensions.typo3.org/extension/extension_builder/
