### ISSUE TITLE
Add admin registration approval

### ISSUE THREAD

**Issue by colorcube** [saschaende/typo3-users#28]
Sometimes user registration is not open to everyone. Which means an administrator wants to check the registration and then enable the user (or not).

I think it should work like this:

- the registration plugin needs an option "admin registration approval needed"
- the registration plugin needs a field for (multiple?) admin email adresses
- the mail text to the user needs to be different: "further approval required bla bla"
- the plugin message after clicking the activation link needs to be different: "further approval required bla bla"
- approval email has to be send to admins 
- approval email has links "activate" and "reject"
- "reject" will send an email to user "sorry rejected" and delete the user record?
- "activate" will send an email to user "you're accepted" with a link to login page

Is this something which is in the works? Otherwise I might look into it myself.

**Comment by saschaende** [comment]
Hi,

sorry, nothing is planned in this direction at the moment. But you are free to help out with developing the extension.

**Comment by colorcube** [comment]
Working version is here:

https://github.com/colorcube/typo3-users

It's all working but needs a final review and some translations to english. Which I hope to do in the next days.

Comments welcome.

Will send a pull request when ready.

**Comment by saschaende** [comment]
Wow incredible. I will then check your pull and and add you to the list of coworkers.

**Comment by saschaende** [comment]
Du bist ja aus Hannover? :D Haha gibts ja nich.
