### ISSUE TITLE
Username and Email Address Enumeration

### ISSUE THREAD

**Issue by typo3ua** [saschaende/typo3-users#3]
Is it taken into count in your extension?

https://typo3.org/security/advisory/typo3-psa-2019-002/

Thanks!

**Comment by saschaende** [comment]
There will be a feature:

Additional options for user names:
Setting A: Show input field and automatically generate a user name if the user does not enter one.
Setting B: Hide input field and always automatically generate a user name.
Setting C: User name is not generated automatically, input is mandatory.

**Comment by saschaende** [comment]
Login plugin and forgot pass plugin give you no information, if an account exists.

**Comment by saschaende** [comment]
But its a good idea, i will change it for the registration plugin:

- The user gets no feedback, if the email exists. If email exists, the user gets an email with password reset link.

**Comment by saschaende** [comment]
# I updated the readme and todo list, thanks

**Comment by saschaende** [comment]
This is fixed now in version 0.5.2
