### ISSUE TITLE
[FEATURE] possible Login List?

### ISSUE THREAD

**Issue by ineswillenbrock** [saschaende/typo3-users#31]
Hi there,
would it be possible, to implement something like this view with/into this extension?

[https://docs.typo3.org/typo3cms/extensions/festat/0.8.2/Introduction/Index.html](https://docs.typo3.org/typo3cms/extensions/festat/0.8.2/Introduction/Index.html)

That could be a nice way to have everythink on one place - and less extension clutter in the installation :)

Thank you!

kind regards - Ines

**Comment by saschaende** [comment]
Yes, a list view (including basic search) for users is planned.

**Comment by ineswillenbrock** [comment]
Great, would that show the IP of the login and possibly the time online?

**Comment by saschaende** [comment]
No, this feature is not planned, because i do not need it fpr myself.

**Comment by ineswillenbrock** [comment]
Would sponsoring be possible? Either money or code? The IP would be nice to have to keep an eye on suspicious logins.

**Comment by saschaende** [comment]
You can either program the function yourself and contribute to the code or order the function - the normal hourly rates (100 €/h) apply here.

**Comment by saschaende** [comment]
Anyway, the last login is already saved yet in this version (if you use the users login module). Just have a look into the users tab.

**Comment by ineswillenbrock** [comment]
Thanks for the last hint, I found a way to get what I need.
