### ISSUE TITLE
Feature: universal e-mail styling

### ISSUE THREAD

**Issue by kledo-34** [saschaende/typo3-users#32]
Hey there,
while I was working with your extension I thought about why not having a way to style all emails of typo3 or just the users extension without changing the html templates in the code. (This might also be a task for typo3/form, but I don't have an account on forge.typo3.org so I won't report it over there ;) )
I found myself overwriting e-mail templates of various extensions, e.g. users, form, aimeos, etc. although I didn't need to change the text, it was only the header, footer and css, so I thought, why not having a backend module in typo3 with 3 fields, one html field to write your custom e-mail header, one html field to write your custom e-mail footer and one css field for css for the body of the e-mail. In this way the extension could stay 100% updatable wihtout changing original code and if now all extensions with e-mails would take the header, footer and css from there it would be a super handy way to manage your companies e-mails design. One more feature in here could be that you could have a layout variation for different e-mails, e.g. a shop e-mail needs bank account details in the footer, while a contact form e-mail doesn't, but nevertheless, this doesn't seem to be a super complicated feature, but would be super handy and save a LOT of time to handle all different e-mails of different extensions and I would not need to worry anymore about new e-mails coming on updates (like the last users update) that I have to take care and style again, because they would fetch the general design automatically. Of course there would probably be a need of having some class naming conventions, but I guess this is not too complicated to figure out.
(By the way the aimeos extension already has a good approach by giving you an email.css file in your custom theme that will be added to the e-mails, which is kind of a first step into such a direction, but of course header, footer and general style for all mails is not archieved here yet).
Maybe you think this would be a great feature, I hope so ;)

**Comment by saschaende** [comment]
Yes, i am already working on an extension to unify all emails for all extensions with one viewhelper.

**Comment by saschaende** [comment]
The name of the new extension will be "emailthemes"

**Comment by kledo-34** [comment]
Yeah, thanks a lot, this was unexpected, I didn't know someone is already working on this.
Thank you for creating such a solution, I really appreciate that.

**Comment by saschaende** [comment]
I did not tell anybody about that :D

**Comment by kledo-34** [comment]
Hey there, 
I saw you implemented "emailthemes", but where can I get this extension? I didn't find it in TER, github, packagist, etc.
Apart from that, very cool that this gets started ;)

**Comment by saschaende** [comment]
> Hey there,
> I saw you implemented "emailthemes", but where can I get this extension? I didn't find it in TER, github, packagist, etc.
> Apart from that, very cool that this gets started ;)

TYPO3 30 will have this by default:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.3/Feature-90266-Fluid-basedTemplatedEmails.html

So i stopped working on this extension.

**Comment by kledo-34** [comment]
Oh yeah cool, I'm definitely not up to date with typo 3 10, but you should probably  remove the "emailthemes" dependency from the ter extension as this could lead to confusion. Thanks for your work anyways :)

**Comment by saschaende** [comment]
Yes, thats a good hint. Will do that :)
