### ISSUE TITLE
Get/Post parameters are lost when logging in or out

### ISSUE THREAD

**Issue by Beltshassar** [saschaende/typo3-users#33]
When using login plugin on a page with other plugins, all the plugin url-parameters are removed from the url.

felogin have the option: preserveGETvars wich keeps the parameters. Is it possible to do something similar in typo3-users?

https://docs.typo3.org/c/typo3/cms-felogin/master/en-us/Configuration/Index.html#preservegetvars

Best regards 
Daniel Damm

**Comment by saschaende** [comment]
Yes, would be easily possible.... but why do you want to do this?

**Comment by Beltshassar** [comment]
Thankyou for a fast response!

I am working on a site, where users need to log in, before buying access to a virtual product.
I have a single log-in form present in the header of all pages.

If I go to the product page (from the cart_products ext.) and log in, the tx_cartproducts_products[product] parameter disappears and the cart_product plugin won't know which product I was looking at before the log in.

Same thing happens when I log in, while visiting a tx_news detail-view, which we also use quite a lot.

**Comment by saschaende** [comment]
Will implement this for the next version.

**Comment by Beltshassar** [comment]
Thank's @saschaende that sounds really great!
