### ISSUE TITLE
About the field 'usergroup'

### ISSUE THREAD

**Issue by typo3ua** [saschaende/typo3-users#34]
Add new field
TS:
```
plugin.tx_users {
    settings {
        fields {
            11 {
                key = usergroup
                name = Usergroup
                type = select
            }
        }
    }
}
```
PHP:
```
class Registration extends \SaschaEnde\Users\Domain\Model\Registration
{
    /**
     * @var
     */
    protected $usergroup;

    /**
     * @return
     */
    public function getUsergroup() {
        return $this->usergroup;
    }

    /**
     * @param $usergroup
     */
    public function setUsergroup($usergroup) {
        $this->usergroup = $usergroup;
    }
}
```
HTML/FLUID:
```
<div class="form-group">
    <label for="usergroup">
        <f:translate key="register.field.usergroup" extensionName="ukrainian_package"/><f:if condition="{field.required}">*</f:if>
    </label>
    <f:form.select
            id="usergroup"
            property="usergroup"
            class="form-control{f:if(condition: '{errors.usergroup}',then: ' is-invalid')}{f:if(condition: '{errors} && !{errors.usergroup}',then: ' is-valid')}"
            options="{
                4: 'TYPO3 Developer',
                5: 'TYPO3 Integrator',
                6: 'TYPO3 Editor',
                7: 'TYPO3 Consultant'
            }"
            prependOptionLabel="{f:translate(key: 'register.field.usergroup.chose', extensionName: 'ukrainian_package')}"
            prependOptionValue=""
            additionalAttributes="{autocomplete:'new-password'}"
    />
    <div class="text-danger">
        <f:for each="{errors.usergroup}" as="errorcode">
            <div><f:render partial="Validation" section="error{errorcode}"/></div>
        </f:for>
    </div>
</div>
```
After submitting the selected value in the field does not save and not add in the database and deletes the current value in the field `usergroup` of frontend user, after this, I get error `401 Authorization Required`

**Comment by saschaende** [comment]
I think because there is already a setting in the plugin, where you can set the usergroup for registration: "Usergroup(s) for new users".

**Comment by saschaende** [comment]
Idea to accomplish this more easy: Just make 4 registration pages - for every group?

**Comment by typo3ua** [comment]
Thanks for the reply. 

> ....where you can set the `usergroup` for registration: `Usergroup(s) for new users`

Yes, I know about the `Usergroup(s) for new users` this as the `usergroup` of the `default group` and it is good.

But except `User Group{s) for new users` I need **additional** `usergroup` for each frontend user, which the user chooses for himself in moment registration or when edits own profile...

> Idea to accomplish this more easy: Just make 4 registration pages - for every group?

Thank you... That is interesting but I think that is not good, at least for me.
I think that better and more convenient to add an additional frontend group.

As I guess this opportunity will not be in the extension in the future?

**Comment by saschaende** [comment]
For security reasons this MUST be editable in the plugin settings, because otherwise everybody can change the ID in the select menu and then for example gain admin rights. Another popular user extension had this issue.

So i think best would be:

1. Add usergroups in the plugin settings
2. Make a checkbox "Let the user decide, which group to chose"

This would be secure, because the user can chose only from the available groups AND the group will be checked after submitting the form.

**Comment by typo3ua** [comment]
Thanks for the reply.
Yes, I agree with you security is very important.

> 1. Add usergroups in the plugin settings
> 2. Make a checkbox "Let the user decide, which group to chose"
>
> This would be secure, because the user can chose only from the available groups AND the group > will be checked after submitting the form.

That is a great idea... I have to try it... I will write about it here when I make it...
