### ISSUE TITLE
User dashboard

### ISSUE THREAD

**Issue by p380** [saschaende/typo3-users#4]
is planned to integrate dashboard for FE users where user has a option to make a custom homepage (drag&drop a widget, add a new element)

regards

**Comment by saschaende** [comment]
What do you think, should be on this dashboard? Any ideas are welcome.

**Comment by saschaende** [comment]
Profiles are planned. With some description, user data, image...

**Comment by p380** [comment]
It is meant that the user can customize the website (sample: the entry page with content or user profile).
An example of using the gridstackjs library.

**Comment by saschaende** [comment]
The extension "Users" is a foundation to build your own community. The extension contains all necessary tools for user administration.

A website generator does not belong to it and is also not planned.
