### ISSUE TITLE
I can not save plugin option (pi_flexform)

### ISSUE THREAD

**Issue by typo3ua** [saschaende/typo3-users#5]
Hello!

I test `ext:user` on the TYPO3 version 9.5.6

### I did
- I installed `ext:users`
- Added `ext:users` to main template
- Added new content element with `ext: users -> users_register`
- Click `Save`
- I get it `Alert "The fields marked with an exclamation mark are not yet correctly filled in. Please complete them properly."`

![new_user_ext_user](https://user-images.githubusercontent.com/638022/57544257-827f9f00-735f-11e9-884c-44a011256828.png)

### I have:
- ` TYPO3` version 9.5.6
- `PHP` version 7.2
- `ext:users` version 0.5.3
- `ext:t3helpers` version 0.9.25

**Comment by saschaende** [comment]
Interesting that the extension also works in TYPO3 9 yet.

But the error you submitted also seems to be in TYPO3 8, i will immediately go into it and post an update as soon as possible.

**Comment by saschaende** [comment]
It is fixed now, new release 0.5.4 is released just now.

**Comment by saschaende** [comment]
Did you test all the plugins with TYPO3 9? If you did this succesfully i could upgrade the version number for TYPO3 9... this information would be very helpful!

**Comment by typo3ua** [comment]
Yes, I updated it. Now is works well.

**Comment by typo3ua** [comment]
I will be to test yet other functions in the TYPO3 9
