### ISSUE TITLE
The icons are missing in all forms

### ISSUE THREAD

**Issue by typo3ua** [saschaende/typo3-users#6]
![icons_form_ext_user](https://user-images.githubusercontent.com/638022/57549157-74378000-736b-11e9-898b-fab054d813cf.png)

**Comment by saschaende** [comment]
You need "fontawesome" to display the icons.

**Comment by typo3ua** [comment]
Is there way another for getting Icons? Maybe better add an alternative.

**Comment by saschaende** [comment]
You can change the template and add your own. Most websites have any icon library installed.

**Comment by saschaende** [comment]
Bootstrap 4 is also recommending fontawesome: https://getbootstrap.com/docs/4.3/extend/icons/

**Comment by typo3ua** [comment]
Okay! I understood, need only the custom CSS. Thanks!

**Comment by saschaende** [comment]
An idea is, to make the classes for icons configurable via TYPOSCRIPT. Will add this.

**Comment by typo3ua** [comment]
I know, thanks!

**Comment by saschaende** [comment]
You are in luck, today i am working on this extension. Check out new version: https://github.com/saschaende/typo3-users/releases/tag/0.5.5

**Comment by typo3ua** [comment]
I will try to add other icons, not `fontawesome` using this option. I will inform about it when I to do it.

**Comment by saschaende** [comment]
Now its very easy, just check the TYPOSCRIPT. Change it like this:

`plugin.tx_users {
    view {
        templateRootPaths.0 = EXT:users/Resources/Private/Templates/
        partialRootPaths.0 = EXT:users/Resources/Private/Partials/
        layoutRootPaths.0 = EXT:users/Resources/Private/Layouts/
    }
    settings {
        // Configure icon span css classes for different templates (actually fontawesome)
        iconClassUser = fas fa-user fa-fw
        iconClassPassword = fas fa-lock fa-fw
        iconClassEmail = fas fa-envelope fa-fw
        iconClassRegister = fas fa-user-plus fa-fw
    }
}`

**Comment by typo3ua** [comment]
Yes, It is well but...

I think need to create a proposal for display icons, for example
1. Form without icons
2. Form with Icons based on files
3. Form with Icons based on CSS (`fontawesome` or other)
