### ISSUE TITLE
Check users for spam hosts - Not work

### ISSUE THREAD

**Issue by typo3ua** [saschaende/typo3-users#7]
### In the backend:

![check_user_be_ext_user](https://user-images.githubusercontent.com/638022/57584201-47a57480-74e1-11e9-900b-9af597eabbe8.png)

### I see...

![error_check_user_be_ext_user](https://user-images.githubusercontent.com/638022/57584224-71f73200-74e1-11e9-9d3f-9875c8be2b59.png)

TYPO3 9.5.6

**Comment by saschaende** [comment]
Did you update the database befor? ("import newest spamhost banlist")

Without the database, checking users makes no sense.

**Comment by typo3ua** [comment]
Okay! Then, in this case, the user must see some information and not the error. For example "Hints" or something other...

**Comment by saschaende** [comment]
You should not get an error now with the MASTER version (here on github). I will release 0.5.6 when the two new plugins are ready.

See commit:
https://github.com/saschaende/typo3-users/commit/4fe1051841da85d6c485e9464b7257268fde617d

**Comment by typo3ua** [comment]
Okay! I understand. Thanks!

**Comment by typo3ua** [comment]
I installed 0.6.0beta  from here... for the present everything well
